version: '3.2'

services:
   elasticsearch:
      image: elasticsearch:7.8.0
      volumes:
        - type: bind
          source: ./elasticsearch/elasticsearch.yml
          target: /usr/share/elasticsearch/config/elasticsearch.yml
          read_only: true
      ports:
       - "9200:9200"
       - "9300:9300"
      environment:
       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
       ELASTIC_PASSWORD: "1234"
       discovery.type: single-node
      networks:
       - elk
   
   filebeat:
      build:
       context: dateappWithBeat/
      ports:
       - "27015:22/tcp"
      networks:
       - elk
      depends_on:
       - elasticsearch
       - logstash
       - kibana

   logstash:
      image: logstash:7.8.0
      volumes:
      - type: bind
        source: ./logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      ports:
       - "5000:5000/tcp"
       - "5000:5000/udp"
       - "9600:9600"
      environment:
       LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
       - elk
      depends_on:
       - elasticsearch

   kibana:
      image: kibana:7.8.0
      volumes:
       - type: bind
         source: ./kibana/kibana.yml
         target: /usr/share/kibana/config/kibana.yml
         read_only: true
      ports:
        - "5601:5601"
      networks:
        - elk
      depends_on:
        - elasticsearch


networks:
  elk:
    driver: bridge
